@startuml
entity TB_media_types {
    * Id: INTERGER
    Name: NVARCHAR(120)
}

entity TB_genres {
    * id: INTERGER
    Name: NVARCHAR(140)
}

entity TB_playlists {
    * id: INTERGER
    Name: NVARCHAR(120)
}

entity TB_playlist_track {
    * Playlistid <<FK>>
    * Trackid <<FK>>
}
   Playlistid referencia TB_playlists
   Trackid referencia TB_tracks

entity TB_tracks {
    * id: INTERGER
    Name: NVARCHAR(200)
    Albumid: INTERGER <<FK>>
    MediaTypeid <<FK>>
    Genreid: INTERGER
    Composer: NVARCHAR(220)
    Milliseconds: INTERGER
    Bytes: INTERGER
    UnitPrice: NUMERIC
}
   Albumid referencia TB_albums
   MediaTypeId referencia TB_media_types

entity TB_artists {
    * id: INTERGER
    Name: NVARCHAR(120)
}

entity TB_invoices {
    * id: INTERGER
    Customerid: INTERGER <<FK>>
    InvoiceDate: DATETIME
    BillingAddress: NVARCHAR
    BillingCity: NVARCHAR
    4 more columns...
}
   Customerid referencia TB_customers

entity TB_invoice_items {
    * id: INTERGER
    Invoiceid: INTERGER <<FK>>
    Trackid: INTERGER <<FK>>
    UnitPrice: NUMERIC
    Quantity: INTERGER
}
   Invoiceid referencia TB_invoices
   Trackid referencia TB_tracks
   

entity TB_albums {
    * id: INTERGER
    Title: NVARCHAR(160)
    Artistid: INTERGER <<FK>>
}
   Artistid referencia TB_artists

entity TB_customers {
    * id: INTERGER
    FirstName: NVARCHAR(40)
    LastName: NVARCHAR(20)
    Company: NVARCHAR(80)
    Adress: NVARCHAR(70)
    City: NVARCHAR(40)
    State: NVARCHAR(40)
    Country: NVARCHAR(40)
    PostalCode: NVARCHAR(10)
    Phone: NVARCHAR(24)
    Fax: NVARCHAR(24)
    Email: NVARCHAR(60)

}

entity TB_employees {
    * id: INTERGER
    LastName: NVARCHAR(20)
    FirstName: NVARCHAR(20)
    Title: NVARCHAR(30)
    ReportsTo: INTERGER
    BirthDate: DATETIME
    HireDate: DATETIME
    Address: NVARCHAR(70)
    7 more columns...
}

TB_media_types ||--o{ TB_tracks
TB_genres |o--o{ TB_tracks
TB_tracks ||--o| TB_playlist_track
TB_playlist_track |o--|| TB_playlists
TB_tracks }o--o| TB_albums
TB_albums }o--|| TB_artists
TB_tracks ||--o{ TB_invoice_items
TB_invoice_items }o--|| TB_invoices
TB_invoices }o--|| TB_customers
TB_customers }o--o| TB_employees
TB_employees }o--o{ TB_employees
@enduml
